interface FalImageResult {
  url: string;
  width: number;
  height: number;
}

export async function generateImageWithFal(
  prompt: string,
  sceneImageUrl: string,
  productImageUrl: string,
  resolution: string = "1024x1024"
): Promise<FalImageResult> {
  try {
    if (!process.env.FAL_API_KEY) {
      throw new Error("FAL_API_KEY is not configured");
    }
    const [width, height] = resolution.split('x').map(Number);
    
    console.log("Fal.ai request details:", {
      promptLength: prompt.length,
      promptPreview: prompt.substring(0, 200) + "...",
      fullPrompt: prompt, // عرض البرومبت كامل
      sceneImageUrl,
      productImageUrl,
      width,
      height
    });
    
    // Try SDXL Inpainting with minimal required parameters
    const response = await fetch("https://fal.run/fal-ai/stable-diffusion-xl-inpainting", {
      method: "POST",
      headers: {
        "Authorization": `Key ${process.env.FAL_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        prompt: `${prompt} Professional CGI quality, photorealistic, ultra-detailed`,
        image_url: sceneImageUrl, // Scene to edit  
        negative_prompt: "blurry, low quality, distorted, artifacts, cartoon, anime, sketch",
        strength: 0.8, // How much to change
        num_inference_steps: 25,
        guidance_scale: 7.5,
        enable_safety_checker: true,
      }),
    });

    if (!response.ok) {
      const errorBody = await response.text();
      console.error('Fal.ai API error details:', {
        status: response.status,
        statusText: response.statusText,
        body: errorBody
      });
      throw new Error(`Fal.ai API error: ${response.status} - ${errorBody}`);
    }

    const result = await response.json();
    
    if (!result.images || result.images.length === 0) {
      throw new Error("No images generated by Fal.ai");
    }

    return {
      url: result.images[0].url,
      width: result.images[0].width,
      height: result.images[0].height,
    };
  } catch (error) {
    console.error("Fal.ai API error:", error);
    throw new Error("Failed to generate image with Fal.ai");
  }
}
